import * as fs from 'fs-extra';
import * as path from 'path';
import inquirer from 'inquirer';

const AVAILABLE_COMPONENTS = [
  'button',
  'input',
  'card',
  'switch',
  'dialog',
  'tooltip',
  'select',
  'checkbox',
  'radio-group',
  'textarea',
  'badge',
  'alert'
];

const COMPONENT_FILES = {
  button: [
    'button.component.ts',
    'button.metadata.ts'
  ],
  input: [
    'input.component.ts',
    'input.metadata.ts'
  ],
  card: [
    'card.component.ts',
    'card.metadata.ts'
  ],
  switch: [
    'switch.component.ts',
    'switch.metadata.ts'
  ],
  dialog: [
    'dialog.component.ts',
    'dialog.service.ts',
    'dialog.metadata.ts'
  ],
  tooltip: [
    'tooltip.component.ts',
    'tooltip.directive.ts',
    'tooltip.metadata.ts'
  ],
  select: [
    'select.component.ts'
  ],
  checkbox: [
    'checkbox.component.ts'
  ],
  'radio-group': [
    'radio-group.component.ts'
  ],
  textarea: [
    'textarea.component.ts'
  ],
  badge: [
    'badge.component.ts'
  ],
  alert: [
    'alert.component.ts'
  ]
};

export async function installComponent(
  componentName: string,
  options: { path: string; mode: string }
) {
  console.log(`🚀 Installing ${componentName} component...`);

  // Validate component name
  if (!AVAILABLE_COMPONENTS.includes(componentName)) {
    console.error(`❌ Component "${componentName}" not found.`);
    console.log(`Available components: ${AVAILABLE_COMPONENTS.join(', ')}`);
    process.exit(1);
  }

  // Check if Angular project
  if (!fs.existsSync('angular.json')) {
    console.error('❌ This is not an Angular project. Please run this command in an Angular project root.');
    process.exit(1);
  }

  // Confirm installation
  const { confirm } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'confirm',
      message: `Install ${componentName} component to ${options.path}/${componentName}?`,
      default: true
    }
  ]);

  if (!confirm) {
    console.log('Installation cancelled.');
    return;
  }

  try {
    // Create destination directory
    const destDir = path.join(process.cwd(), options.path, componentName);
    await fs.ensureDir(destDir);

    // Get source directory - for development, go up from cli/dist to root, then to packages
    const sourceDir = path.join(__dirname, '..', '..', '..', 'packages', componentName, 'src', 'lib');
    
    // Copy component files
    const files = COMPONENT_FILES[componentName as keyof typeof COMPONENT_FILES];
    
    for (const file of files) {
      const sourcePath = path.join(sourceDir, file);
      const destPath = path.join(destDir, file);
      
      if (await fs.pathExists(sourcePath)) {
        await fs.copy(sourcePath, destPath);
        console.log(`✅ Copied ${file}`);
      } else {
        console.warn(`⚠️  Source file not found: ${sourcePath}`);
      }
    }

    // Create index file
    const indexContent = generateIndexFile(componentName, files, options.mode);
    await fs.writeFile(path.join(destDir, 'index.ts'), indexContent);
    console.log(`✅ Created index.ts`);

    // Copy README
    const readmePath = path.join(__dirname, '..', '..', '..', 'packages', componentName, 'README.md');
    if (await fs.pathExists(readmePath)) {
      await fs.copy(readmePath, path.join(destDir, 'README.md'));
      console.log(`✅ Copied README.md`);
    }

    console.log(`🎉 Successfully installed ${componentName} component!`);
    console.log(`\n📁 Files installed to: ${destDir}`);
    console.log(`\n📖 Usage:`);
    console.log(`import { ${getComponentClassName(componentName)} } from './${options.path}/${componentName}';`);

  } catch (error) {
    console.error('❌ Installation failed:', error);
    process.exit(1);
  }
}

function generateIndexFile(componentName: string, files: string[], mode: string): string {
  const exports = files
    .filter(file => file.endsWith('.ts'))
    .map(file => {
      const name = file.replace('.ts', '');
      return `export * from './${name}';`;
    })
    .join('\n');

  return `// Generated by ng-shadcn CLI
// Component: ${componentName}
// Mode: ${mode}

${exports}
`;
}

function getComponentClassName(componentName: string): string {
  return componentName.charAt(0).toUpperCase() + componentName.slice(1) + 'Component';
}